server:
  port: 80

#nacos的配置
spring:
  application:
    name: seata-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

#设置ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

#配置seata
#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
#  tx-service-group: my_test_tx_group
#  config:
#    type: nacos
#    # 需要和server在同一个注册中心下
#    nacos:
#      serverAddr: localhost:8848
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
#      server-addr: localhost:8848
#      username: "nacos"
#      password: "nacos"


management:
  endpoints:
    web:
      exposure:
        include: "*"

