server:
  port: 80

#nacos的配置
spring:
  application:
    name: seata-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

management:
  endpoints:
    web:
      exposure:
        include: "*"


##seata的配置
#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  service:
#    #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
#    vgroup-mapping:
#      my_test_tx_group: default
#      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
#    grouplist:
#      default: 127.0.0.1:8091
#  #      disable-global-transaction: false
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      #这里的地址就是你的nacos的地址,可以更换为线上
#      serverAddr: 127.0.0.1:8848
#      #这里的名字就是registry.conf中 nacos的group名字
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      #这里的地址就是你的nacos的地址,可以更换为线上
#      server-addr: 127.0.0.1:8848
#      #这里的名字就是registry.conf中 nacos的group名字
#      group: SEATA_GROUP
#      namespace:
#      userName: "nacos"
#      password: "nacos"
