server:
  port: 80

#nacos的配置
spring:
  application:
    name: seata-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

management:
  endpoints:
    web:
      exposure:
        include: "*"

