server:
  port: 80


spring:
  application:
    name: cloud-alibaba-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"
