server:
  port: 80

spring:
  application:
    name: feign80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/ ,http://eureka-server7002.com:7002/eureka/


#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#openFeign日志
logging:
  level:
    com.boot.feignService.UserFeignService: debug