server:
  port: 80

spring:
  application:
    name: feign80
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/ ,http://eureka-server7002.com:7002/eureka/


#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 7000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 7000

#openFeign日志
logging:
  level:
    com.boot.feignService.UserFeignService: debug

#开启Feign和Hystrix的支持，因为默认Feign对Hystrix是不支持的
feign:
  hystrix:
    enabled: true
